# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Workout watch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Workout watch
pod 'UICircularProgressRing'
pod 'Firebase/Core'
 pod 'Firebase/AdMob'

  target 'Workout watchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Workout watchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
